## Arrays


- array can store data of same time
- unique index
- size of array is predefine


### type of arrays
- one dimentional
- multi-dimentional

In [1]:
from array import *

In [2]:
arr1 = array('i', [1,2,3,4,5])

In [3]:
arr1

array('i', [1, 2, 3, 4, 5])

In [4]:
type(arr1)

array.array

In [5]:
arr2 = array('d',[1.3,1.5])

In [6]:
arr2

array('d', [1.3, 1.5])

time complexcity of array here is o(1)

In [8]:
arr1.insert(5,7)

In [9]:
arr1

array('i', [1, 2, 3, 4, 5, 7])

In [10]:
arr1.insert(0,0)

In [11]:
arr1

array('i', [0, 1, 2, 3, 4, 5, 7])

In [12]:
arr1.insert(2,8)

In [13]:
arr1

array('i', [0, 1, 8, 2, 3, 4, 5, 7])

## array travisal

In [14]:
def traversaArray(array):
    for i in array:
        print(i)
traversaArray(arr1)

0
1
8
2
3
4
5
7


def traversaArray(array):
    for i in array: o(n)
        print(i) o(1)
traversaArray(arr1)
time-complecity = o(n)

## accessing array element

In [18]:
def access_element(array, index):
    if index >= len(array):
        print("index is out of range")
    else:
        print(array[index])
        
access_element(arr1,9)

index is out of range


# searching element in array

- binary search
- simple with index
- looking every element - time inefficent



In [20]:
def search_array_every_element(array, value):
    for i in array:
        if i == value:
            return array.index(value)
        else:
            continue
    return "sorry its not present"

search_array_every_element(arr1,35)
            

'sorry its not present'

loop = o(n) and for if o(1) time complexcity is on 

## deleting an element for an array

In [21]:
arr1.remove(1)

In [22]:
arr1

array('i', [0, 8, 2, 3, 4, 5, 7])

## array oprations

In [24]:
# create an array and travese 

my_array = array('i',[1,2,3,4,5])

for i in my_array:
    print(i)

1
2
3
4
5


In [26]:
# access indivial elements throgh indexes
my_array[0]

1

In [27]:
# TRY APPEND METHOD append add at the last
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6])

In [28]:
# insert method insert(index, value)
my_array.insert(0, 0)

In [29]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 6])

In [30]:
# extend python array using extand
my_array_new = array('i', [7,8,9])
my_array.extend(my_array_new)

In [32]:
# add items from list into using fromlist()
temp_list = [20,21,22]
my_array.fromlist(temp_list)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22])

## two dimentional array


day 1 - 11, 15, 10, 6
day 1 - 11, 15, 10, 6
day 1 - 11, 15, 10, 6
day 1 - 11, 15, 10, 6

In [33]:
import numpy as np

In [34]:
two_d_array = np.array([[11,15,10,6],[1,2,3,4],[45,54,22,32], [12,34,56,43]])

In [35]:
two_d_array

array([[11, 15, 10,  6],
       [ 1,  2,  3,  4],
       [45, 54, 22, 32],
       [12, 34, 56, 43]])

In [37]:
# adding coloum
# adding row
#t-c o(mn)
new_two_d_array = np.insert(two_d_array, 0, [[1,2,3,4]], axis=0)
new_two_d_array


array([[ 1,  2,  3,  4],
       [11, 15, 10,  6],
       [ 1,  2,  3,  4],
       [45, 54, 22, 32],
       [12, 34, 56, 43]])

### accessing in two d array

In [39]:
def access_two_d_array(array, r_index, c_index):
    if r_index >= len(array) or c_index >= len(array[0]):
        print('index is out of range')
    else:
        return array[r_index][c_index]
    
access_two_d_array(two_d_array,1,2)

3

In [40]:
two_d_array

array([[11, 15, 10,  6],
       [ 1,  2,  3,  4],
       [45, 54, 22, 32],
       [12, 34, 56, 43]])

In [42]:
access_two_d_array(two_d_array,2,2)

22

# traversel 2-d array

In [44]:
def tre_two_d_arr(array):
    for i in array:
        for j in i:
            print(j)
tre_two_d_arr(two_d_array)

11
15
10
6
1
2
3
4
45
54
22
32
12
34
56
43


## searching in 2-d array


In [47]:
def search_two_d_array(array,value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if value == array[i][j]:
                
                return ' the value is' + str(i)+" "+str(j)
    return 'sorry'
search_two_d_array(two_d_array, 3)

' the value is1 2'

# python list

### accessing in list

In [48]:
s_list = ['milk','row','buttor']
s_list[0]

'milk'

In [50]:
for i in range(len(s_list)):
    s_list[i] = s_list[i] + '+'

In [51]:
s_list

['milk+', 'row+', 'buttor+']

## project 1 avg temprature


In [54]:
numDays = int(input('how many days temp'))
total = 0
for i in range(1, numDays+1):
    nextDay = int(input("day" +str(i)+ 'temp'))
    total += nextDay
avg = round(total/numDays,2)
avg

how many days temp2
day1temp3
day2temp3


3.0

find all pair which is equal to 9

In [58]:
my_list = [2,3,4,5,6,7,8,9]
def find_pairs(nums, target):
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                print(i,j)
            
find_pairs(my_list,10)

0 6
1 5
2 4


In [60]:
myArray = np.array([1,2,3,4,5,6,7,8,9,0,12,34,4])

def findNumber(array, target):
    for i in range(len(array)):
        if array[i] == target:
            print(i)
findNumber(myArray, 4)

3
12


In [64]:
def maxProduct(array):
    max_value = 0
    for i in range(len(array)):
        for j in range(i+1,len(array)):
            if array[i] * array[j] > max_value:
                max_value = array[i] * array[j]
                paris = str(array[i]) + ' '+ str(array[j])
    print(paris)
    print(max_value)
maxProduct(myArray)    

12 34
408


In [69]:
myArray = np.array([1,2,3,4,5,6,7,8,9,0,12,34])
def unique(array):
    for i in range(len(array)):
        for j in range(i+1, len(array)):
            if array[i] == array[j]:
                print('not ')
                return
    else:
        print('yes')
unique(myArray)

yes


In [ ]:
def permutation(list1, list2):
    if len(list1) != len(list2):
        return False
    else:
        